/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.4 at Wed Jan 29 21:47:27 2014. */

#include "messages.pb.h"



const pb_field_t SensorData_fields[8] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC, FIRST, SensorData, id, id, 0),
    PB_FIELD2(  2, BOOL    , OPTIONAL, STATIC, OTHER, SensorData, binding, id, 0),
    PB_FIELD2(  3, FLOAT   , OPTIONAL, STATIC, OTHER, SensorData, temperature, binding, 0),
    PB_FIELD2(  4, INT32   , OPTIONAL, STATIC, OTHER, SensorData, battery_level, temperature, 0),
    PB_FIELD2(  5, FLOAT   , OPTIONAL, STATIC, OTHER, SensorData, pressure, battery_level, 0),
    PB_FIELD2(  6, FLOAT   , OPTIONAL, STATIC, OTHER, SensorData, humidity, pressure, 0),
    PB_FIELD2(  7, INT32   , OPTIONAL, STATIC, OTHER, SensorData, type, humidity, 0),
    PB_LAST_FIELD
};


