/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.4 at Mon Feb 17 22:38:18 2014. */

#include "messages.pb.h"



const pb_field_t PiWeather_SensorData_fields[8] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC, FIRST, PiWeather_SensorData, id, id, 0),
    PB_FIELD2(  2, BOOL    , OPTIONAL, STATIC, OTHER, PiWeather_SensorData, binding, id, 0),
    PB_FIELD2(  3, FLOAT   , OPTIONAL, STATIC, OTHER, PiWeather_SensorData, temperature, binding, 0),
    PB_FIELD2(  4, INT32   , OPTIONAL, STATIC, OTHER, PiWeather_SensorData, battery_level, temperature, 0),
    PB_FIELD2(  5, FLOAT   , OPTIONAL, STATIC, OTHER, PiWeather_SensorData, pressure, battery_level, 0),
    PB_FIELD2(  6, FLOAT   , OPTIONAL, STATIC, OTHER, PiWeather_SensorData, humidity, pressure, 0),
    PB_FIELD2(  7, INT32   , OPTIONAL, STATIC, OTHER, PiWeather_SensorData, type, humidity, 0),
    PB_LAST_FIELD
};

const pb_field_t PiWeather_BindingAck_fields[3] = {
    PB_FIELD2(  1, INT32   , REQUIRED, STATIC, FIRST, PiWeather_BindingAck, id, id, 0),
    PB_FIELD2(  2, INT32   , OPTIONAL, STATIC, OTHER, PiWeather_BindingAck, time_interval_s, id, 0),
    PB_LAST_FIELD
};


